### ISSUE TITLE
Fix hellfire smelting of smeltry with glue

### ISSUE THREAD

**Issue by Glease** [Team-AbCiv/TinkersEvolution#1]
I may write a more generic solution to this problem. But for now please just use glue to fix it.

<sub>I don't feel well now. Please excuse me for not doing this all by myself.

**Comment by 3TUSK** [comment]
> Now I hate my mod name as it's far too generic

**Comment by Glease** [comment]
Thx, but ... Why everyone hate to close an issue?

**Comment by 3TUSK** [comment]
> Remember me to write a issue processing streamline guide...

**Comment by 3TUSK** [comment]
Issue persist to be fixed...

**Comment by 3TUSK** [comment]
Managed to fix this, I guess
