### ISSUE TITLE
Arrow can't peierce through clouds in the end

### ISSUE THREAD

**Issue by Glease** [Team-AbCiv/TinkersEvolution#2]
It's now very hard, if not impossible, to slain the dragon, since any long range weapon is effectively paralyzed. Please either make cloud destoryed by arrows or make arrows/bolts can go through clouds.

**Comment by 3TUSK** [comment]
Disable cloud gen?

**Comment by 3TUSK** [comment]
The End will have no cloud. ~~Enojy~~ Enjoy
