### ISSUE TITLE
A true tool parts forging system

### ISSUE THREAD

**Issue by 3TUSK** [Team-AbCiv/TinkersEvolution#7]
Imagine that you have to make TCon tool parts *à la TerraFirmaCraft forging system*. While you can always use casting, that only gives you average quality.

Will definitely require a new mod to achieve this.

To-do list
* [ ] The mod
  * [ ] An anvil
  * [ ] Flux?
  * [ ] Hammer
  * [ ] An algorithm for giving special effect on tool parts
  * [ ] A way to make those special effects effective upon tool being built
* [ ] If we can update to 1.11, try integrate with Vazkii's Skillable
* [ ] Consider about darkhax's Game Stages
* [ ] Tough As Nail temperature system.

Contents subject to change.

**Comment by Glease** [comment]
Please considering adding quenching.

Some segments of background info: Forging is a primitive version of modern metal shaping, and even in ancient times, forging is always companied with quenching, a still viable part of modern thermal treatment. It's just far more advanced, complex and precise.

--- Original Message ---

**Comment by 3TUSK** [comment]
Definitely will add this. "Forging" is used to refer the whole process. Any better terminology?

**Comment by Glease** [comment]
It seems quite irrelevant to consider TAN temperature. When your metal is at 1000K+, the difference between 320K, and 250K will make little difference.

<sub>It'll be a completely theory if there is *lots of* lava around.</sub>

--- Original Message ---

**Comment by Glease** [comment]
Like, metallurgy?

**Comment by 3TUSK** [comment]
That includes making alloys, doesn't it

> For context: see below. old comments are vanished

**Comment by Glease** [comment]
Like, metallurgy?

It also seems quite irrelevant to consider TAN temperature. When your metal is at 1000K+, the difference between 320K, and 250K will make little difference.

<sub>It'll be a completely theory if there is *lots of* lava around. It will also be different if there is rain dropping onto your metal.</sub>

<sub>I'm not going to reply with mail again. It has neither  markdown rendering nor html rendering.</sub>

**Comment by Glease** [comment]
Keynotes:
1. TAN temperature is actually rated between 0 and 25. If the actual temperature overflows, use 25, and 0 for underflow. You start to take damage when below 3 or above 22.
2. Some ideas on *how to craft a tool*:

    0. Prepare wooden/leather parts.
    1. melt the metal
    2. make alloy *
    2. Cast it into a good shape. - All metal needs casting. No casting -> extremely long forging - This step  can barely do anything to change the end result. (If the cast is bad, the result may be bad, if no appropriate forging is used)
    3. Forge it with a hammer - the tool part need to be kept at a good temp, and there are a lot of forging     methods. All have its advantages and disadvantages. - A multi-step process. Multiple forging method can be applied to one piece of tool part. However they will interact with each other and not all these side effects is welcomed. *
    4. Quenching, tempering. - Just timing and fire temperature controlling.*
    5. Somehow "glue" the parts together. Give it a name if you likes.

    Those postfixed with a star is optional.

**Comment by 3TUSK** [comment]
Sidenote: Only `TinkerEvent.OnItemBuilding` can be used, but it does not carry the input item stacks (i.e. the tool parts used in tool building). 

Appendix: or implement our own tool forge.

Appendix: or just use ASM to hook into TCon. *Last resort only*

**Comment by 3TUSK** [comment]
https://reddit.com/r/feedthebeast/comments/8o33wq

**Comment by 3TUSK** [comment]
https://old.reddit.com/r/feedthebeast/comments/9smxdn

**Comment by 3TUSK** [comment]
https://minecraft.curseforge.com/projects/tinkers-forging
This one looks promising.

**Comment by Glease** [comment]
The wheel of history rolls forward. Indeed it's slow, but it does roll.

**Comment by 3TUSK** [comment]
> Although this one doesn't use flux, and this one can't affect the overall quality of parts. ~~Want change? Fork it~~
