### ISSUE TITLE
Nutrition

### ISSUE THREAD

**Issue by 3TUSK** [Team-AbCiv/TinkersEvolution#8]
Yes, Nutrition. You cannot just eat bread all the way through the game, right?
https://github.com/WesCook/Nutrition

**Comment by Glease** [comment]
So... bread with that fruit salad? We don't have a pasture for now, and all we have is a hole for chicks

--- Original Message ---

**Comment by 3TUSK** [comment]
You forget veges.

**Comment by Glease** [comment]
Early game? You aren't going to get any of those unless you are super lucky to get either spawned near a village or get one from a zombie.

--- Original Message ---

**Comment by 3TUSK** [comment]
Tough question. Might make early-game more peaceful? Starter item kit?

**Comment by Glease** [comment]
FTBU got a integrated starting item mechanism. But I don't think adding vegetable seeds to it would be a good idea. It makes adding this mod more like an annoyance rather than usefulness/joy.

Anyway, I vote down on this idea.

**Comment by 3TUSK** [comment]
Note in case forgetting: there is config that can control nutrition decay. We may slow down it to a realistic value...

**Comment by 3TUSK** [comment]
Let's say this is rejected for now... it might be in the *expert mode* version, but definitely not enabled by default.
