### ISSUE TITLE
Port to 1.11+

### ISSUE THREAD

**Issue by 3TUSK** [Team-AbCiv/TinkersEvolution#9]
#Just a reminder

* [X] Better With Mods
* [X] Chisel & Bites
* [X] Foamfix http://asie.pl/Projects/Minecraft/Mods/FoamFix/
* [X] Forestry -> This one should be removed
* [X] FTBUtils
* [X] Glue -> ~~It's not hard at all~~ https://github.com/Team-AbCiv/Glue/tree/1.11
* [X] JEI
* [X] Meltery
* [X] Persistent Bits
* [X] Natura - Test build exists, while it's still alpha; also, unless it gets along with TAN, I may consider about either nuke it or use InsanePatcher on it
* [ ] Railcraft - remember me do disable some modules in it
* [ ] RTG?
* [X] Storage Drawers
* [X] Timberjack
* [X] Tinkers Construct
* [X] Tinker Tool Leveling
* [X] Tough As Nail - serious question: this mod seems inactive as for now, consider forking it
* [X] Twilight Forest. There is test build floating around, but that's still ***test build*** and might cause everything explode

**Comment by 3TUSK** [comment]
Update:
C&B, Natura, Storage Drawers, Timberjack, TinkerToolLeveling and TAN has 1.11 builds. Check

**Comment by 3TUSK** [comment]
Also, Glue has potential to run on 1.10.2, 1.11.2 and 1.12 without re-compiling. Need to check that.

**Comment by Glease** [comment]
> Railcraft - remember me do disable some modules in it

disable what?

**Comment by 3TUSK** [comment]
Decoration. Those stuff occupies block ids :)

**Comment by Glease** [comment]
OK. And what problem is natura having with TAN? I don't feel like if there is anything went wrong.

**Comment by 3TUSK** [comment]
Barley. Can it grow in cold weather IRL?

Addendum: in fact, TAN should just take ICrop and try doing something on it.

**Comment by Glease** [comment]
If you want RTG you may just pregenerate chunks in 1.10.2 and then move the world to 1.11. I recall there should be some mods to help do this.

**Comment by 3TUSK** [comment]
I suspect that RTG is optional - check out OpenTerrainGenerator.

**Comment by 3TUSK** [comment]
Update:
asie uploaded the Foamfix 0.7.0 (beta!), suitable for 1.10.2, 1.11.2 and 1.12.

**Comment by 3TUSK** [comment]
Update: https://github.com/Team-AbCiv/Glue/tree/1.11

**Comment by 3TUSK** [comment]
Oh I found this: https://jenkins.gildedgames.com/job/Aether-1.10/
One more option: Aether II. Progression should be after TwilightForest if it will be in this pack.

**Comment by 3TUSK** [comment]
No 1.11 is not the future, but 1.12 is. Probably not worth a new issue but we will see...

**Comment by Glease** [comment]
Well, good luck with that one!

--- Original Message ---
